### ISSUE TITLE
MarketRegistry

### ISSUE THREAD

**Issue by jaycenhorton** [nori-dot-eco/NIPs#3]
## Preamble

    NIP: <to be assigned>
    Title: NRC-3 MarketRegistry
    Author: jaycen@nori.eco
    Type: Standard Track
    Category: Core 
    Status: Draft
    Created: 2017-12-17

## Simple Summary
The specification for a MarketRegistry (as outlined in [ERC-2](https://github.com/nori-dot-eco/NIPs/issues/2)) provides the necessary functionalities of a Market registry smart contract. It should contain a list of all registered markets.

## Abstract
Registries allow listing and searching of markets and can serve as connector between markets.
## Motivation
Having a smart contract acting as a registry of available markets allows for interoperability between markets and allows for a simple standard for an ecosystem of markets. A market registry can also just contain a singular market, such as will be the case of the Nori Carbon Removal Credit market, whilst still allowing different types of functionalities in similar markets.

## Specification
 <img src="https://www.lucidchart.com/publicSegments/view/02e1ee49-85cb-40fb-b639-e092f2ab98dc/image.png">

### MarketRegistry
Market registries contain information about markets. There is at least one global registry (though other may create more like the global Registry) to which you can add your market. Adding your market to it would increase the experience of the user that the GUI Client can use or not.

This specification outlines the necessary implementation details for a MarketRegistry smart contract

#### Market
```
struct Market {
  address addr;
  string name;
  address owner;
  address participantRegistry;
  address commodityRegistry;
  mapping (bytes32 => bytes32) meta;
}
```
A Market struct contains an address of the actual Market contract containing market functionalities, the name of the market, the address which owns the particular Market, a commodity and participant registry associated with a Market, and a mapping with metadata about the Market which can be used to lookup more information on the particular market.

#### markets
`Market[] markets;`
An array containing all registered Markets

#### getMarket
```
getMarket(uint _index) constant returns(address addr, string name, address owner, address participantRegistry, address commodityRegistry){
  var m = markets[_index];
  addr = m.addr
  name = m.name;
  owner = m.owner; 
  participantRegistry = m.participantRegistry;
  commodityRegistry = m.commodityRegistry;
}
```
Returns Market information based on its index.
#### getMarketFromAddress
```
getMarketFromAddress(address _addr) constant returns(address addr, string name, address owner, address participantRegistry, address commodityRegistry){
  var m = markets[_addr];
  addr = m.addr
  name = m.name;
  owner = m.owner; 
  participantRegistry = m.participantRegistry;
  commodityRegistry = m.commodityRegistry;
}
```
Returns Market information based on an address
#### getMarketFromOwner
```
getMarketFromOwner(address _owner) constant returns(address addr, string name, address owner, address participantRegistry, address commodityRegistry){
  var m = markets[_owner];
  addr = m.addr;
  name = m.name;
  owner = m.owner; 
  participantRegistry = m.participantRegistry;
  commodityRegistry = m.commodityRegistry;
}
```
Returns Market information based on an owner address
#### getMarketFromName
```
getMarketFromName(string _name) constant returns(address addr, string name, address owner, address participantRegistry, address commodityRegistry){
  var m = markets[_name];
  addr = m.addr;
  name = m.name;
  owner = m.owner; 
  participantRegistry = m.participantRegistry;
  commodityRegistry = m.commodityRegistry;
}
```
#### getMarketFromParticipantRegistry
```
getMarketFromParticipantRegistry(address _participantRegistry) constant returns(address addr, string name, address owner, address participantRegistry, address commodityRegistry){
  var m = markets[_participantRegistry];
  addr = m.addr;
  name = m.name;
  owner = m.owner; 
  participantRegistry = m.participantRegistry;
  commodityRegistry = m.commodityRegistry;
}
```
Returns Market information based on a Participant Registry
#### getMarketFromCommodityRegistry
```
getMarketFromCommodityRegistry(address _commodityRegistry) constant returns(address addr, string name, address owner, address participantRegistry, address commodityRegistry){
  var m = markets[_commodityRegistry];
  addr = m.addr;
  name = m.name;
  owner = m.owner; 
  participantRegistry = m.participantRegistry;
  commodityRegistry = m.commodityRegistry;
}
```
Returns Market information based on a Commodity Registry
#### getCount
```
getCount() constant returns(uint){
  returns(markets.length); 
}
```
Returns the count of registered markets in the MarketRegistry contract
#### getMeta
```
function meta(uint _index, bytes32 _key) constant returns (bytes32) {
  return markets[_index].meta[_key];
}
```
Returns a multiaddress string referencing an external resource bundle that contains (optionally localized) metadata about the market associated with _index. The string MUST be an IPFS or HTTP(S) base path (without a trailing slash) to which specific subpaths are obtained through concatenation. (IPFS is the preferred format due to better scalability, persistence, and immutability.)
## Rationale
Designing a market registry in this order allows for a user to look up available markets within an ecosystem.

## Backwards Compatibility
To be completed

## Test Cases
To be completed

## Implementation
To be completed

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

**Comment by pcardune** [comment]
I don’t understand. If you want to look something up in an array using
anything other than the index, don’t you need to use a mapping of that
other thing to the index in an array? Or do a linear search? Also, can one
owner own multiple markets? If so then getMarketFromOwner would need to
return an array of markets right?

**Comment by jaycenhorton** [comment]
@pcardune ah, yeah you're right. I wanted the registration mapping functions to take place in the MarketFactory contract, in which case it might just be best to remove those functions for now.

**Comment by pcardune** [comment]
I’m still confused about the nomenclature of factories and types. We should
discuss tomorrow.

**Comment by jaycenhorton** [comment]
For the record of github, a factory contains functions to create a new type and update a registry, a type implements an interface with basic functionality and can be extended by other contracts

Example, you would use a CommodityFactory to register a new CommodityType of ERC-721 (non fungible token: aka CRC). You might later also register a commodityType of ERC-20 and update the registry accordingly.
